# This is a GitHub Actions workflow file for Continuous Integration (CI)
# It runs automatically when changes are pushed or pull requests are opened against the "main" branch.

name: Node.js CI

# When to run the workflow
on:
  push:
    branches: [ main ]           # Runs on push to "main"
  pull_request:
    branches: [ main ]           # Runs on PRs targeting "main"

jobs:
  build:                         # Name of the job
    runs-on: ubuntu-latest       # Use the latest Ubuntu runner

    # Strategy allows us to test across multiple Node.js versions
    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Define versions of Node.js to test against

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    # Step to clone your repo code into the runner

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1  # Install the specified Node.js version
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci                  # Faster, cleaner install using package-lock.json

    - name: Build (if script is defined)
      run: npm run build --if-present  # Will only run if you have a "build" script

    - name: Run tests
      run: npm test               # Run test script defined in package.json

